In [1]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import finesse
from finesse.analysis.actions import RunLocks, Noxaxis, Xaxis
from finesse import ligo
# from LLOF3NoSqz_Anamaria import make_LLOANA
from LLOF3NoSqz import make_LLO


finesse.configure(plotting=True)

In [2]:
LIGO = finesse.Model()
LIGO.parse_file("./LIGO_degisn.txt")

# LLOANA = make_LLOANA(LIGO.deepcopy())
LLObase = make_LLO(LIGO.deepcopy())

In [3]:
LLObase.L0.P, LLObase.lmich.value

(<L0.P=40.0 @ 0x112edc340>, <lmich.value=5.342 @ 0x15b2bbb80>)

In [4]:
LLObase.print_mismatches()

╒════════════════════════════╤════════════════╤════════════════╕
│ Coupling                   │   Mismatch (x) │   Mismatch (y) │
╞════════════════════════════╪════════════════╪════════════════╡
│ BS.p1.i -> BS.p2.o         │    2.91307e-05 │    3.30789e-05 │
├────────────────────────────┼────────────────┼────────────────┤
│ BS.p2.i -> BS.p1.o         │    2.91307e-05 │    3.30789e-05 │
├────────────────────────────┼────────────────┼────────────────┤
│ BS.p2.i -> BS.p4.o         │    4.27427e-05 │    0.000637753 │
├────────────────────────────┼────────────────┼────────────────┤
│ BS.p3.i -> BS.p4.o         │    6.75304e-05 │    0.000448204 │
├────────────────────────────┼────────────────┼────────────────┤
│ BS.p4.i -> BS.p3.o         │    6.75304e-05 │    0.000448204 │
├────────────────────────────┼────────────────┼────────────────┤
│ BS.p4.i -> BS.p2.o         │    4.27427e-05 │    0.000637753 │
├────────────────────────────┼────────────────┼────────────────┤
│ ITMX.p1.i -> ITMX.p2.o 

In [5]:
LLObase.PRM.Rc, LLObase.PR2.Rc, LLObase.PR3.Rc, LLObase.SRM.Rc, LLObase.SR2.Rc, LLObase.SR3.Rc, \
LLObase.ETMX.Rc, LLObase.ETMY.Rc, LLObase.ITMX.Rc, LLObase.ITMY.Rc,

(array([11.009, 11.009]),
 array([-4.545, -4.545]),
 array([36.027, 36.027]),
 array([-5.673, -5.673]),
 array([-6.406, -6.406]),
 array([35.97, 35.97]),
 array([2247.71, 2247.71]),
 array([2245.4, 2245.4]),
 array([-1937.9, -1937.9]),
 array([-1940.7, -1940.7]))

In [6]:
# Anamaria's numbers
LLO = LLObase.deepcopy()
# LLO.lp1.L = 16.609     # PRM to PR2
# LLO.lp2.L = 16.166     # PR2 to PR3
# LLO.lp3.L = 19.538     # PR3 to BS

# LLO.ls3.L = 19.452
# LLO.ls2.L = 15.457
# LLO.ls1.L = 15.759                   


# LLO.lmich.value = 5.344
# LLO.lschnupp.value = 0.085

# LLO.PRM.Rc = 11
# LLO.PR2.Rc = -4.555
# LLO.PR3.Rc = 36
# LLO.SRM.Rc = -5.6938
# LLO.SR2.Rc = -6.427
# LLO.SR3.Rc = 36
# LLO.ETMX.Rc = 2242
# LLO.ETMY.Rc = 2242
# LLO.ITMX.Rc = -1934
# LLO.ITMY.Rc = -1934

# LLO.ITMX.T = 0.0148
# LLO.ITMY.T = 0.0148
# LLO.PRM.T = 0.031
# LLO.BS.T = 0.5
# LLO.PR2.T = 250e-6
# LLO.PR3.T = 5e-6
# LLO.SR3.T = 5e-6
# LLO.SR2.T = 5e-6
# LLO.SRM.T = 0.324
# LLO.ETMX.T = 4e-6
# LLO.ETMY.T = 4e-6

# LLO.Mloss.value = 37.5e-6;
# loss = 37.5e-6
# LLO.BS.L = loss
# LLO.PRM.L = loss*3
# LLO.PR2.L = loss
# LLO.PR3.L = loss
# LLO.SR3.L = loss
# LLO.SR2.L = loss
# LLO.SRM.L = loss

LLO.ETMX.L = 44e-6 # From Anamaria's email
LLO.ETMY.L = 44e-6
LLO.ITMX.L = 25e-6
LLO.ITMY.L = 25e-6


# LLO.ITMXAR.R = 20e-6
# LLO.ITMYAR.R = 20e-6
# LLO.BSAR1.R = 20e-6
# LLO.PRMAR.R = 20e-6
# # LLO.PR2.R = 20e-6
# # LLO.PR3.R = 20e-6
# # LLO.SR3.R = 20e-6
# # LLO.SR2.R = 20e-6
# LLO.SRMAR.R = 20e-6
# LLO.ETMXAR.R = 20e-6
# LLO.ETMYAR.R = 20e-6

# LLO.ITMX.mass = 40
# LLO.ITMY.mass = 40
# LLO.BS.mass = 14
# LLO.PRM.mass = 2.9
# LLO.PR2.mass = 2.9
# LLO.PR3.mass = 12
# LLO.SR3.mass = 12
# LLO.SR2.mass = 2.9
# LLO.SRM.mass = 2.9
# LLO.ETMX.mass = 40
# LLO.ETMY.mass = 40

# # LLO.OMCa.T = 0.01
# # LLO.OMCa.L = 10e-6
# # LLO.OMCa.ROC = 2.5
# # LLO.OMCa.AoI = 0
# # LLO.OMCa.Rar = 10e-6

# LLO.mod1.midx = 0.14
# LLO.mod2.midx = 0.15

LLO.L0.P, LLO.lmich.value

(<L0.P=40.0 @ 0x15b1b0e80>, <lmich.value=5.342 @ 0x15b5be700>)

In [7]:
LLO.print_mismatches()

╒════════════════════════════╤════════════════╤════════════════╕
│ Coupling                   │   Mismatch (x) │   Mismatch (y) │
╞════════════════════════════╪════════════════╪════════════════╡
│ BS.p1.i -> BS.p2.o         │    2.91307e-05 │    3.30789e-05 │
├────────────────────────────┼────────────────┼────────────────┤
│ BS.p2.i -> BS.p4.o         │    4.27427e-05 │    0.000637753 │
├────────────────────────────┼────────────────┼────────────────┤
│ BS.p2.i -> BS.p1.o         │    2.91307e-05 │    3.30789e-05 │
├────────────────────────────┼────────────────┼────────────────┤
│ BS.p3.i -> BS.p4.o         │    6.75304e-05 │    0.000448204 │
├────────────────────────────┼────────────────┼────────────────┤
│ BS.p4.i -> BS.p3.o         │    6.75304e-05 │    0.000448204 │
├────────────────────────────┼────────────────┼────────────────┤
│ BS.p4.i -> BS.p2.o         │    4.27427e-05 │    0.000637753 │
├────────────────────────────┼────────────────┼────────────────┤
│ ITMX.p1.i -> ITMX.p2.o 

In [8]:
# kat1 = LLO.deepcopy()
kat1 = LLO.deepcopy()
kat1.DARM.DC = 0.0033834586466165405/2 # So that the DARM offset is 10 pm. (check?)
kat1.parse("""
pd Pin PRMAR.p1.i
pd PRefl PRMAR.p1.o
pd PPoP PR2.p3.o
pd PAS SRMAR.p2.o


ad PoPC PR2.p3.o f=0
ad PoP9P PR2.p3.o f=&f1
ad PoP9M PR2.p3.o f=-&f1
ad PoP45P PR2.p3.o f=&f2
ad PoP45M PR2.p3.o f=-&f2


ad ReflC PRMAR.p1.o f=0
ad Refl9P PRMAR.p1.o f=&f1
ad Refl9M PRMAR.p1.o f=-&f1
ad Refl45P PRMAR.p1.o f=&f2
ad Refl45M PRMAR.p1.o f=-&f2

ad ASC SRMAR.p2.o f=0
ad AS9P SRMAR.p2.o f=&f1
ad AS9M SRMAR.p2.o f=-&f1
ad AS45P SRMAR.p2.o f=&f2
ad AS45M SRMAR.p2.o f=-&f2
""")

# outLLO1 = kat1.run(Noxaxis(pre_step=RunLocks(method='newton', 
#                                             display_progress=True,
#                                             max_iterations=1000)))

outLLO1 = kat1.run(Noxaxis())

print()
print("##################### The results: #####################")
print(f"The input power (into PRM) is {outLLO1['Pin']} W")
print(f"The Refl port power is {outLLO1['PRefl']} W")
print(f"The PoP port power is {outLLO1['PPoP']} W")
print(f"The AS port power is {outLLO1['PAS']} W")

print()

print(f"The power in the carrier at PoP is {np.abs(outLLO1['PoPC'])**2} W")
print(f"The power in the 9MHz upper sideband at PoP is {np.abs(outLLO1['PoP9P'])**2} W")
print(f"The power in the 9MHz lower sideband at PoP is {np.abs(outLLO1['PoP9M'])**2} W")
print(f"The power in the 45MHz upper sideband at PoP is {np.abs(outLLO1['PoP45P'])**2} W")
print(f"The power in the 45MHz lower sideband at PoP is {np.abs(outLLO1['PoP45M'])**2} W")
print()

print(f"The power in the carrierz at Refl is {np.abs(outLLO1['ReflC'])**2} W")
print(f"The power in the 9MHz upper sideband at Refl is {np.abs(outLLO1['Refl9P'])**2} W")
print(f"The power in the 9MHz lower sideband at Refl is {np.abs(outLLO1['Refl9M'])**2} W")
print(f"The power in the 45MHz upper sideband at Refl is {np.abs(outLLO1['Refl45P'])**2} W")
print(f"The power in the 45MHz lower sideband at Refl is {np.abs(outLLO1['Refl45M'])**2} W")
print()

print(f"The power in the carrier at AS is {np.abs(outLLO1['ASC'])**2} W")
print(f"The power in the 9MHz upper sideband at AS is {np.abs(outLLO1['AS9P'])**2} W")
print(f"The power in the 9MHz lower sideband at AS is {np.abs(outLLO1['AS9M'])**2} W")
print(f"The power in the 45MHz upper sideband at AS is {np.abs(outLLO1['AS45P'])**2} W")
print(f"The power in the 45MHz lower sideband at AS is {np.abs(outLLO1['AS45M'])**2} W")


##################### The results: #####################
The input power (into PRM) is 39.99588353876745 W
The Refl port power is 2.250316846559399 W
The PoP port power is 0.4633033295731256 W
The AS port power is 0.3742439373281985 W

The power in the carrier at PoP is 0.45256428692053896 W
The power in the 9MHz upper sideband at PoP is 0.004730138128137707 W
The power in the 9MHz lower sideband at PoP is 0.004730137572166747 W
The power in the 45MHz upper sideband at PoP is 0.0006393887578968239 W
The power in the 45MHz lower sideband at PoP is 0.0006393781943854505 W

The power in the carrierz at Refl is 1.9079501774804275 W
The power in the 9MHz upper sideband at Refl is 0.1451411223277213 W
The power in the 9MHz lower sideband at Refl is 0.14514109488256594 W
The power in the 45MHz upper sideband at Refl is 0.026041881662421523 W
The power in the 45MHz lower sideband at Refl is 0.02604257020626239 W

The power in the carrier at AS is 0.04510970190964393 W
The power in the 9MHz up

## Power recyling gain: the ratio of stored laser power in the power-recycling cavity to input laser power


$$\mathrm{PRG = \frac{P_{circ\, in\, PRC}}{P_{in}}}$$

In [16]:
# kat2 = LLO.deepcopy()
kat2 = LLO.deepcopy()
kat2.DARM.DC = 0.0033834586466165405/2 # So that the DARM offset is 10 pm. (check?)

kat2.parse("""
pd Pin PRMAR.p1.i
pd Pcirc PRM.p2.o
#pd Pcirc PR2.p2.o

""")

# outLLO2 = kat2.run(Noxaxis(pre_step=RunLocks(method='newton', 
#                                             display_progress=True,
#                                             max_iterations=1000)))

outLLO2 = kat2.run(Noxaxis())

print()
print("##################### The results: #####################")

print(f"The input power (into PRM) is {outLLO2['Pin']} W")
print(f"The PRC circulating power is {outLLO2['Pcirc']} W")
print(f"Their ratio (PRG) is {outLLO2['Pcirc']/outLLO2['Pin']}")


##################### The results: #####################
The input power (into PRM) is 39.99588353876745 W
The PRC circulating power is 1906.5980640869361 W
Their ratio (PRG) is 47.669857380170065
